-- Create the password_resets table to store OTP codes and request details
CREATE TABLE IF NOT EXISTS public.password_resets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifier TEXT NOT NULL,          -- The email or phone number entered
    email TEXT,                        -- The user's primary email (for linking)
    phone_number TEXT,                 -- The user's phone number (for linking)
    type TEXT NOT NULL,                -- 'email' or 'phone'
    code TEXT NOT NULL,                -- The 6-digit OTP code
    requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_verified BOOLEAN DEFAULT FALSE
);

-- Add index for faster lookups during verification
CREATE INDEX IF NOT EXISTS idx_password_resets_identifier_code ON public.password_resets(identifier, code);

-- Enable Row Level Security (optional but recommended)
ALTER TABLE public.password_resets ENABLE ROW LEVEL SECURITY;

-- Allow service role or authenticated users to insert/select as needed
CREATE POLICY "Enable all for public" ON public.password_resets FOR ALL TO anon USING (true) WITH CHECK (true);

-- Function to automatically link email and phone during password reset request
CREATE OR REPLACE FUNCTION public.link_auth_identifiers()
RETURNS TRIGGER AS $$
BEGIN
    -- If email is missing but identifier is a phone number, try to find email
    IF NEW.email IS NULL AND NEW.type = 'phone' THEN
        SELECT email INTO NEW.email FROM public.users WHERE phone_number = NEW.identifier;
    END IF;
    
    -- If phone_number is missing but identifier is an email, try to find phone
    IF NEW.phone_number IS NULL AND NEW.type = 'email' THEN
        SELECT phone_number INTO NEW.phone_number FROM public.users WHERE email = NEW.identifier;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to run before every insert into password_resets
DROP TRIGGER IF EXISTS trg_link_auth_identifiers ON public.password_resets;
CREATE TRIGGER trg_link_auth_identifiers
BEFORE INSERT ON public.password_resets
FOR EACH ROW
EXECUTE FUNCTION public.link_auth_identifiers();

-- ============================================================
-- AI Search: Add ai_description column to media table
-- ============================================================
-- This column stores AI-generated descriptions of media content
-- for semantic search (e.g., searching "teddy" finds images with teddy bears)

ALTER TABLE public.media ADD COLUMN IF NOT EXISTS ai_description TEXT;

-- Create index for faster text search on AI descriptions
CREATE INDEX IF NOT EXISTS idx_media_ai_description 
ON public.media USING gin(to_tsvector('english', COALESCE(ai_description, '')));
