// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'database/entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5419065009772418613),
    name: 'MemoryEvent',
    lastPropertyId: const obx_int.IdUid(11, 175472150240486583),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7560595817942957781),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8409742368456743506),
        name: 'startTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5311234575496934226),
        name: 'endTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8476445174406607350),
        name: 'filePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4847399348641968219),
        name: 'modality',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5853333624825209124),
        name: 'sessionId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 317423172475970202),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(4, 6975913763885735414),
        hnswParams: obx_int.ModelHnswParams(dimensions: 4096),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6556520708834070217),
        name: 'isEncrypted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1738019590539624900),
        name: 'encryptionNonce',
        type: 23,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2297200818070377809),
        name: 'wrappedKey',
        type: 23,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 175472150240486583),
        name: 'ephemeralPublicKey',
        type: 23,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4185059925301627990),
    name: 'ObjectState',
    lastPropertyId: const obx_int.IdUid(6, 1633470029791658417),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4642508790064033161),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7957561996451269815),
        name: 'label',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 9041875230264802186),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 808149527731651179),
        name: 'lastConfirmedEventId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2507673799817020538),
        name: 'lastConfirmedTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8398991025973331228),
        name: 'confirmationType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1633470029791658417),
        name: 'confidenceScore',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6340600280594907136),
    name: 'TranscriptSegment',
    lastPropertyId: const obx_int.IdUid(6, 7518913697003177708),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7134374581283889853),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5342041396071069843),
        name: 'eventId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 6207687665632590218),
        relationTarget: 'MemoryEvent',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5628552671694844074),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7333511925337701755),
        name: 'startOffsetMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4799638530371142915),
        name: 'endOffsetMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7518913697003177708),
        name: 'vector',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(5, 4247545234082449233),
        hnswParams: obx_int.ModelHnswParams(dimensions: 4096),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 3331124592311319228),
    name: 'VisualFrame',
    lastPropertyId: const obx_int.IdUid(5, 7862711847645451624),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 869410515118267421),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7263907025108968283),
        name: 'eventId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 2201924458068094333),
        relationTarget: 'MemoryEvent',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 937793197676722048),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6088043542076167897),
        name: 'detectedObjectsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7862711847645451624),
        name: 'vector',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(6, 7719073029953934020),
        hnswParams: obx_int.ModelHnswParams(dimensions: 4096),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 3331124592311319228),
    lastIndexId: const obx_int.IdUid(6, 7719073029953934020),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    MemoryEvent: obx_int.EntityDefinition<MemoryEvent>(
      model: _entities[0],
      toOneRelations: (MemoryEvent object) => [],
      toManyRelations: (MemoryEvent object) => {},
      getId: (MemoryEvent object) => object.id,
      setId: (MemoryEvent object, int id) {
        object.id = id;
      },
      objectToFB: (MemoryEvent object, fb.Builder fbb) {
        final filePathOffset = fbb.writeString(object.filePath);
        final modalityOffset = fbb.writeString(object.modality);
        final sessionIdOffset = fbb.writeString(object.sessionId);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        final encryptionNonceOffset = object.encryptionNonce == null
            ? null
            : fbb.writeListInt8(object.encryptionNonce!);
        final wrappedKeyOffset = object.wrappedKey == null
            ? null
            : fbb.writeListInt8(object.wrappedKey!);
        final ephemeralPublicKeyOffset = object.ephemeralPublicKey == null
            ? null
            : fbb.writeListInt8(object.ephemeralPublicKey!);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.startTime.millisecondsSinceEpoch);
        fbb.addInt64(2, object.endTime.millisecondsSinceEpoch);
        fbb.addOffset(3, filePathOffset);
        fbb.addOffset(4, modalityOffset);
        fbb.addOffset(5, sessionIdOffset);
        fbb.addOffset(6, embeddingOffset);
        fbb.addBool(7, object.isEncrypted);
        fbb.addOffset(8, encryptionNonceOffset);
        fbb.addOffset(9, wrappedKeyOffset);
        fbb.addOffset(10, ephemeralPublicKeyOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final startTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final endTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final filePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final modalityParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final sessionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final isEncryptedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final encryptionNonceParam = const fb.ListReader<int>(
          fb.Int8Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final wrappedKeyParam = const fb.ListReader<int>(
          fb.Int8Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final ephemeralPublicKeyParam = const fb.ListReader<int>(
          fb.Int8Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final object = MemoryEvent(
          id: idParam,
          startTime: startTimeParam,
          endTime: endTimeParam,
          filePath: filePathParam,
          modality: modalityParam,
          sessionId: sessionIdParam,
          embedding: embeddingParam,
          isEncrypted: isEncryptedParam,
          encryptionNonce: encryptionNonceParam,
          wrappedKey: wrappedKeyParam,
          ephemeralPublicKey: ephemeralPublicKeyParam,
        );

        return object;
      },
    ),
    ObjectState: obx_int.EntityDefinition<ObjectState>(
      model: _entities[1],
      toOneRelations: (ObjectState object) => [],
      toManyRelations: (ObjectState object) => {},
      getId: (ObjectState object) => object.id,
      setId: (ObjectState object, int id) {
        object.id = id;
      },
      objectToFB: (ObjectState object, fb.Builder fbb) {
        final labelOffset = fbb.writeString(object.label);
        final confirmationTypeOffset = fbb.writeString(object.confirmationType);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, labelOffset);
        fbb.addInt64(2, object.lastConfirmedEventId);
        fbb.addInt64(3, object.lastConfirmedTime.millisecondsSinceEpoch);
        fbb.addOffset(4, confirmationTypeOffset);
        fbb.addFloat64(5, object.confidenceScore);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final labelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final lastConfirmedEventIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final lastConfirmedTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final confirmationTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final confidenceScoreParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = ObjectState(
          id: idParam,
          label: labelParam,
          lastConfirmedEventId: lastConfirmedEventIdParam,
          lastConfirmedTime: lastConfirmedTimeParam,
          confirmationType: confirmationTypeParam,
          confidenceScore: confidenceScoreParam,
        );

        return object;
      },
    ),
    TranscriptSegment: obx_int.EntityDefinition<TranscriptSegment>(
      model: _entities[2],
      toOneRelations: (TranscriptSegment object) => [object.event],
      toManyRelations: (TranscriptSegment object) => {},
      getId: (TranscriptSegment object) => object.id,
      setId: (TranscriptSegment object, int id) {
        object.id = id;
      },
      objectToFB: (TranscriptSegment object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        final vectorOffset = object.vector == null
            ? null
            : fbb.writeListFloat32(object.vector!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.event.targetId);
        fbb.addOffset(2, textOffset);
        fbb.addInt64(3, object.startOffsetMs);
        fbb.addInt64(4, object.endOffsetMs);
        fbb.addOffset(5, vectorOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final startOffsetMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final endOffsetMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final vectorParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = TranscriptSegment(
          id: idParam,
          text: textParam,
          startOffsetMs: startOffsetMsParam,
          endOffsetMs: endOffsetMsParam,
          vector: vectorParam,
        );
        object.event.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.event.attach(store);
        return object;
      },
    ),
    VisualFrame: obx_int.EntityDefinition<VisualFrame>(
      model: _entities[3],
      toOneRelations: (VisualFrame object) => [object.event],
      toManyRelations: (VisualFrame object) => {},
      getId: (VisualFrame object) => object.id,
      setId: (VisualFrame object, int id) {
        object.id = id;
      },
      objectToFB: (VisualFrame object, fb.Builder fbb) {
        final detectedObjectsJsonOffset = fbb.writeString(
          object.detectedObjectsJson,
        );
        final vectorOffset = object.vector == null
            ? null
            : fbb.writeListFloat32(object.vector!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.event.targetId);
        fbb.addInt64(2, object.timestamp.millisecondsSinceEpoch);
        fbb.addOffset(3, detectedObjectsJsonOffset);
        fbb.addOffset(4, vectorOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final vectorParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final detectedObjectsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = VisualFrame(
          id: idParam,
          timestamp: timestampParam,
          vector: vectorParam,
          detectedObjectsJson: detectedObjectsJsonParam,
        );
        object.event.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.event.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [MemoryEvent] entity fields to define ObjectBox queries.
class MemoryEvent_ {
  /// See [MemoryEvent.id].
  static final id = obx.QueryIntegerProperty<MemoryEvent>(
    _entities[0].properties[0],
  );

  /// See [MemoryEvent.startTime].
  static final startTime = obx.QueryDateProperty<MemoryEvent>(
    _entities[0].properties[1],
  );

  /// See [MemoryEvent.endTime].
  static final endTime = obx.QueryDateProperty<MemoryEvent>(
    _entities[0].properties[2],
  );

  /// See [MemoryEvent.filePath].
  static final filePath = obx.QueryStringProperty<MemoryEvent>(
    _entities[0].properties[3],
  );

  /// See [MemoryEvent.modality].
  static final modality = obx.QueryStringProperty<MemoryEvent>(
    _entities[0].properties[4],
  );

  /// See [MemoryEvent.sessionId].
  static final sessionId = obx.QueryStringProperty<MemoryEvent>(
    _entities[0].properties[5],
  );

  /// See [MemoryEvent.embedding].
  static final embedding = obx.QueryHnswProperty<MemoryEvent>(
    _entities[0].properties[6],
  );

  /// See [MemoryEvent.isEncrypted].
  static final isEncrypted = obx.QueryBooleanProperty<MemoryEvent>(
    _entities[0].properties[7],
  );

  /// See [MemoryEvent.encryptionNonce].
  static final encryptionNonce = obx.QueryByteVectorProperty<MemoryEvent>(
    _entities[0].properties[8],
  );

  /// See [MemoryEvent.wrappedKey].
  static final wrappedKey = obx.QueryByteVectorProperty<MemoryEvent>(
    _entities[0].properties[9],
  );

  /// See [MemoryEvent.ephemeralPublicKey].
  static final ephemeralPublicKey = obx.QueryByteVectorProperty<MemoryEvent>(
    _entities[0].properties[10],
  );
}

/// [ObjectState] entity fields to define ObjectBox queries.
class ObjectState_ {
  /// See [ObjectState.id].
  static final id = obx.QueryIntegerProperty<ObjectState>(
    _entities[1].properties[0],
  );

  /// See [ObjectState.label].
  static final label = obx.QueryStringProperty<ObjectState>(
    _entities[1].properties[1],
  );

  /// See [ObjectState.lastConfirmedEventId].
  static final lastConfirmedEventId = obx.QueryIntegerProperty<ObjectState>(
    _entities[1].properties[2],
  );

  /// See [ObjectState.lastConfirmedTime].
  static final lastConfirmedTime = obx.QueryDateProperty<ObjectState>(
    _entities[1].properties[3],
  );

  /// See [ObjectState.confirmationType].
  static final confirmationType = obx.QueryStringProperty<ObjectState>(
    _entities[1].properties[4],
  );

  /// See [ObjectState.confidenceScore].
  static final confidenceScore = obx.QueryDoubleProperty<ObjectState>(
    _entities[1].properties[5],
  );
}

/// [TranscriptSegment] entity fields to define ObjectBox queries.
class TranscriptSegment_ {
  /// See [TranscriptSegment.id].
  static final id = obx.QueryIntegerProperty<TranscriptSegment>(
    _entities[2].properties[0],
  );

  /// See [TranscriptSegment.event].
  static final event = obx.QueryRelationToOne<TranscriptSegment, MemoryEvent>(
    _entities[2].properties[1],
  );

  /// See [TranscriptSegment.text].
  static final text = obx.QueryStringProperty<TranscriptSegment>(
    _entities[2].properties[2],
  );

  /// See [TranscriptSegment.startOffsetMs].
  static final startOffsetMs = obx.QueryIntegerProperty<TranscriptSegment>(
    _entities[2].properties[3],
  );

  /// See [TranscriptSegment.endOffsetMs].
  static final endOffsetMs = obx.QueryIntegerProperty<TranscriptSegment>(
    _entities[2].properties[4],
  );

  /// See [TranscriptSegment.vector].
  static final vector = obx.QueryHnswProperty<TranscriptSegment>(
    _entities[2].properties[5],
  );
}

/// [VisualFrame] entity fields to define ObjectBox queries.
class VisualFrame_ {
  /// See [VisualFrame.id].
  static final id = obx.QueryIntegerProperty<VisualFrame>(
    _entities[3].properties[0],
  );

  /// See [VisualFrame.event].
  static final event = obx.QueryRelationToOne<VisualFrame, MemoryEvent>(
    _entities[3].properties[1],
  );

  /// See [VisualFrame.timestamp].
  static final timestamp = obx.QueryDateProperty<VisualFrame>(
    _entities[3].properties[2],
  );

  /// See [VisualFrame.detectedObjectsJson].
  static final detectedObjectsJson = obx.QueryStringProperty<VisualFrame>(
    _entities[3].properties[3],
  );

  /// See [VisualFrame.vector].
  static final vector = obx.QueryHnswProperty<VisualFrame>(
    _entities[3].properties[4],
  );
}
